# Generated by Django 5.1 on 2024-10-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense_splitter_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
