# Generated by Django 5.1 on 2024-10-10 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense_splitter_app', '0003_alter_member_amount_split'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='split',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='split',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='split',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='split',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='Expense_splitter_app.member'),
            preserve_default=False,
        ),
    ]
