# Generated by Django 5.1 on 2024-10-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense_splitter_app', '0004_remove_split_created_at_remove_split_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='split',
            name='amount',
            field=models.FloatField(),
        ),
    ]
