# Generated by Django 5.1 on 2024-10-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense_splitter_app', '0005_alter_split_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='split',
            name='total_amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
