# Generated by Django 5.1 on 2024-10-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense_splitter_app', '0006_split_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='split',
            name='member',
        ),
        migrations.RemoveField(
            model_name='split',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='split',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
