# Generated by Django 5.1 on 2024-10-10 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense_splitter_app', '0007_remove_member_amount_remove_split_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='split',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='Expense_splitter_app.member'),
            preserve_default=False,
        ),
    ]
