# Generated by Django 5.1 on 2024-10-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense_splitter_app', '0008_split_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='split',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
