# Generated by Django 5.1 on 2024-10-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense_splitter_app', '0009_alter_split_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='split',
            old_name='amount',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='split',
            name='member',
        ),
        migrations.AddField(
            model_name='member',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='split',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
