# Generated by Django 5.1 on 2024-10-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense_splitter_app', '0010_rename_amount_split_total_amount_remove_split_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='amount',
            field=models.FloatField(),
        ),
    ]
